"""
PagedKVCache: Manages the blocks belonging to one request and presents them as one continuous KV cache to the model.

This is the bridge between non-contiguous physical blocks
and the contiguous past_key_values HuggingFace expects.

Two operations:
    write_token:  store one new token's KV into current block
    gather:       assemble contiguous tensor from all blocks
                  for HuggingFace forward pass
"""

from __future__ import annotations

import torch 

from transformers.cache_utils import DynamicCache

from forgeserve.page_attention.exception import KVCacheOutOfMemoryError
from forgeserve.page_attention.block import KVBlock
from forgeserve.logger import get_logger

logger = get_logger(__name__)

#Hugging face past_key_values type
PastKeyValues = tuple[tuple[torch.Tensor, torch.Tensor], ...]

class PagedKVCache:
    """
    Per-request KV cache using non-contiguous physical blocks.

    Maintains a block table mapping logical position → physical KVBlock.
    Provides gather() to produce contiguous past_key_values for HuggingFace.

    Args:
        request_id: Unique request identifier for logging.
        initial_blocks: First block(s) allocated by BlockManager.
        block_size: Tokens per block (must match BlockManager).
        num_layers: Number of transformer layers.
    """
    def __init__(
            self,
            request_id: str,
            initial_blocks: list[KVBlock],
            block_size: int, 
            num_layers: int,
    ) -> None:
        self.request_id = request_id
        self.block_size = block_size 
        self.num_layers = num_layers 

        # Block Table: ordered list of physical blocks (Real token index)
        # Index in list = Logical block index (Aloocated in gpu memory)
        self.block_table: list[KVBlock] = list(initial_blocks)

        #Total tokens written so far
        self.seq_len: int = 0 

        logger.debug(
            "PagedKVCache created for request '%s' with %d initial block(s)",
            request_id, len(initial_blocks),
        )


    def write_token(
        self,
        past_key_values,
        token_position: int,
    ) -> None:
        """
        Store one token's K/V values into the current physical KV block.

        What happens:
            1. The model's forward pass produces K/V values for every layer.
            2. past_key_values contains those K/V values:
                Layer 0 → K, V
                Layer 1 → K, V
                Layer 2 → K, V
                ...
            3. We select one token (token_position) from each layer.
            4. We write that token's K/V into the current physical block.
            5. We update how many tokens the block contains and the
            total sequence length of the request.

        Example:
            Suppose the model has 2 layers and we process token T4.

                Layer 0 → K/V for T4 ──┐
                                    ├──→ Physical Block
                Layer 1 → K/V for T4 ──┘

            The block now stores T4's K/V for BOTH layers.

        Important:
            The block stores K/V for multiple layers, but each layer has
            its own K/V slice inside the block.

            KVBlock shape:

                K = (num_layers, num_kv_heads, block_size, head_dim)
                V = (num_layers, num_kv_heads, block_size, head_dim)

        In simple words:
            "Take the K/V generated by every transformer layer for one
            token and store them in this request's current KV block."
        """
        block_index = token_position // self.block_size

        if block_index >= len(self.block_table):
            raise KVCacheOutOfMemoryError(
                f"Block index {block_index} out of range. "
                f"Block table has {len(self.block_table)} blocks. "
                f"Pre-allocation was insufficient for token_position={token_position}."
            )
        
        current_block = self.block_table[block_index]

        if current_block.is_full:
            raise KVCacheOutOfMemoryError(
                    f"Block {block_index} is full at token_position={token_position}. "
                    f"Pre-allocation calculation was incorrect."
                )

        for layer_idx in range(len(past_key_values.layers)):
            layer = past_key_values.layers[layer_idx]

            k = layer.keys  # (1, num_heads, seq_len, head_dim)
            v = layer.values  # (1, num_heads, seq_len, head_dim)

            # Extract single token: (batch=1, num_heads, 1, head_dim)
            # → squeeze to (num_heads, head_dim)
            k_token = k[0, :, token_position, :]
            v_token = v[0, :, token_position, :]

            current_block.write_token(layer_idx, k_token, v_token)

        current_block.increment_filled()
        self.seq_len +=1

    def append_block(self, block: KVBlock) -> None:
        """
        Add a newly allocated block to the block table.
        Called by PagedRuntime when current block is full.
        """
        self.block_table.append(block)

        logger.debug(
            "Request '%s': appended block %d (total blocks: %d)",
            self.request_id, block.block_id, len(self.block_table),
        )

    def gather(self) -> PastKeyValues:
        """
    Reconstruct the request's complete KV cache from its physical blocks.

    Why do we need this?
        The KV cache is stored in physical blocks because of paged storage.

        Example:

            block_size = 4

            Block 4 → T0 T1 T2 T3
            Block 3 → T4

        But HuggingFace expects the KV cache as one contiguous sequence:

            T0 T1 T2 T3 T4

        gather() converts the physical block representation back into
        this logical/contiguous representation.

    What happens:
        1. Go through every transformer layer.
        2. For that layer, go through all blocks belonging to the request.
        3. From each block, take only the valid tokens using num_filled.
           This is important because the last block may not be completely full.
        4. Concatenate the K pieces from all blocks.
        5. Concatenate the V pieces from all blocks.
        6. Add the batch dimension required by HuggingFace.
        7. Store (K, V) for this layer in the result.
        8. Return all layers as a tuple.

    Important:
        A physical block contains K/V for ALL layers.

        gather() processes one layer at a time and combines the
        corresponding portions from all physical blocks.

    In simple words:
        "Take the KV data scattered across this request's physical
        blocks, join it in token order, and return it in the contiguous
        format expected by HuggingFace."

        Returns:
            past_key_values in HuggingFace format:
            tuple of (K, V) per layer
            K shape: (1, num_heads, seq_len, head_dim)

        Performance note:
            This gather has O(seq_len) cost per decode step.
            True PagedAttention (vLLM) eliminates this with a custom
            CUDA kernel that reads blocks directly during attention.
            ForgeServe uses gather for educational clarity.
        """
        if self.seq_len == 0:
            return tuple()

        result = []

        for layer_idx in range(self.num_layers):
            k_parts = []
            v_parts = []

            for block in self.block_table:
                filled = block.num_filled
                if filled == 0:
                    continue 

                #Extract filled portion of this block
                # Shape: (num_heads, filled, head_dim)
                k_part = block.k_cache[layer_idx, :, :filled, :]
                v_part = block.v_cache[layer_idx, :, :filled, :]

                k_parts.append(k_part)
                v_parts.append(v_part)

            # Concatenate along sequence dimension
            # Shape: (num_heads, seq_len, head_dim)
            k_full = torch.cat(k_parts, dim=1)
            v_full = torch.cat(v_parts, dim=1)

            # Add batch dimension for HuggingFace
            # Shape: (1, num_heads, seq_len, head_dim)
            result.append((k_full.unsqueeze(0), v_full.unsqueeze(0)))

        return tuple(result)

    def gather_as_dynamic_cache(self) -> DynamicCache:
        """
        Assemble blocks into a HuggingFace DynamicCache object.

        Modern HuggingFace (4.38+) requires DynamicCache instead of
        raw past_key_values tuples what we have collected from the above function gather() and store in a tuple i.e result which is then passed into the forward pass . DynamicCache wraps the same K/V tensors but provides the Cache interface the model expects
        (get_seq_length, update, etc).

        Returns:
            DynamicCache populated with gathered K/V tensors.
        """
        cache = DynamicCache()

        for layer_idx in range (self.num_layers):
            k_parts = []
            v_parts = []

            for block in self.block_table:
                filled = block.num_filled
                if filled == 0:
                    continue
                #shape: [num_layers, num_heads, block_size, head_dim]
                k_parts.append(block.k_cache[layer_idx, :, :filled, :])
                v_parts.append(block.v_cache[layer_idx, :, :filled, :])

            # SHape:(1, num_heads, seq_len, head_dim)
            k_full = torch.cat(k_parts, dim=1).unsqueeze(0)
            v_full = torch.cat(v_parts, dim=1).unsqueeze(0)

            cache.update(k_full, v_full, layer_idx)

        return cache




        
